/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScrapersRouteImport } from './routes/scrapers'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as MediaSpecsRouteImport } from './routes/media-specs'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ArchivePostIdRouteImport } from './routes/archive.$postId'

const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapersRoute = ScrapersRouteImport.update({
  id: '/scrapers',
  path: '/scrapers',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSpecsRoute = MediaSpecsRouteImport.update({
  id: '/media-specs',
  path: '/media-specs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ArchivePostIdRoute = ArchivePostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ArchiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/media-specs': typeof MediaSpecsRoute
  '/organization': typeof OrganizationRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/runs': typeof RunsRoute
  '/scrapers': typeof ScrapersRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/archive/$postId': typeof ArchivePostIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/media-specs': typeof MediaSpecsRoute
  '/organization': typeof OrganizationRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/runs': typeof RunsRoute
  '/scrapers': typeof ScrapersRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/archive/$postId': typeof ArchivePostIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/media-specs': typeof MediaSpecsRoute
  '/organization': typeof OrganizationRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/runs': typeof RunsRoute
  '/scrapers': typeof ScrapersRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/archive/$postId': typeof ArchivePostIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/archive'
    | '/media-specs'
    | '/organization'
    | '/projects'
    | '/prompts'
    | '/runs'
    | '/scrapers'
    | '/settings'
    | '/targets'
    | '/archive/$postId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/archive'
    | '/media-specs'
    | '/organization'
    | '/projects'
    | '/prompts'
    | '/runs'
    | '/scrapers'
    | '/settings'
    | '/targets'
    | '/archive/$postId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/archive'
    | '/media-specs'
    | '/organization'
    | '/projects'
    | '/prompts'
    | '/runs'
    | '/scrapers'
    | '/settings'
    | '/targets'
    | '/archive/$postId'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  MediaSpecsRoute: typeof MediaSpecsRoute
  OrganizationRoute: typeof OrganizationRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PromptsRoute: typeof PromptsRoute
  RunsRoute: typeof RunsRoute
  ScrapersRoute: typeof ScrapersRoute
  SettingsRoute: typeof SettingsRoute
  TargetsRoute: typeof TargetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrapers': {
      id: '/scrapers'
      path: '/scrapers'
      fullPath: '/scrapers'
      preLoaderRoute: typeof ScrapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-specs': {
      id: '/media-specs'
      path: '/media-specs'
      fullPath: '/media-specs'
      preLoaderRoute: typeof MediaSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/archive/$postId': {
      id: '/archive/$postId'
      path: '/$postId'
      fullPath: '/archive/$postId'
      preLoaderRoute: typeof ArchivePostIdRouteImport
      parentRoute: typeof ArchiveRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchivePostIdRoute: typeof ArchivePostIdRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchivePostIdRoute: ArchivePostIdRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  MediaSpecsRoute: MediaSpecsRoute,
  OrganizationRoute: OrganizationRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PromptsRoute: PromptsRoute,
  RunsRoute: RunsRoute,
  ScrapersRoute: ScrapersRoute,
  SettingsRoute: SettingsRoute,
  TargetsRoute: TargetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
